---
- name: Конфигурация серверов Docker
  hosts: app
  become: true
  tags:
    - docker
  tasks:

########### НАЧАЛО БЛОКА: Конфигурация Docker для ОС Debian ############

    - name: Установка зависимостей
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
      when: ansible_os_family == "Debian" 

    - name: Добавление GPG ключа
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_os_family == "Debian"

    - name: Добавление репозитория Docker
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      when: ansible_os_family == "Debian"

    - name: Установка Docker
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      when: ansible_os_family == "Debian"

########### КОНЕЦ БЛОКА: Конфигурация Docker для ОС Debian ############

########### НАЧАЛО БЛОКА: Конфигурация Docker для ОС RedHat ############

    # - name: Установка зависимостей
    #   ansible.builtin.yum:
    #     name: "{{ item }}"
    #     state: present
    #     update_cache: true
    #   loop:
    #     - apt-transport-https
    #     - ca-certificates
    #     - curl
    #     - gnupg-agent
    #     - software-properties-common
    #   when: ansible_os_family == "RedHat"

    - name: Добавление ключа GPG
      ansible.builtin.rpm_key:
        key: "https://download.docker.com/linux/centos/gpg"
        state: present
      when: ansible_os_family == "RedHat"

    - name: Добавление репозитория Docker
      ansible.builtin.yum_repository:
        name: docker
        description: docker repository
        baseurl: "https://download.docker.com/linux/centos/8/x86_64/stable"
        enabled: true
        gpgcheck: true
        gpgkey: "https://download.docker.com/linux/centos/gpg"
      when: ansible_os_family == "RedHat"

    - name: Установка Docker
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      when: ansible_os_family == "RedHat"

########### КОНЕЦ БЛОКА: Конфигурация Docker для ОС RedHat ############

    - name: Проверка запуска docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

- name: Конфигурация серверов Postgresql-server
  hosts: database
  become: true
  tags:
    - pg
  tasks:

    - name: Добавление GPG ключа
      ansible.builtin.apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Добавление репозитория Postgresql-server
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
        state: present

    - name: Установка Postgresql-server
      ansible.builtin.apt:
        name: "postgresql-{{ pg_version }}"
        state: present
        update_cache: true

    - name: Изменение директории pg data
      ansible.builtin.lineinfile:
        path: /etc/postgresql/12/main/postgresql.conf
        regexp: '^data_directory ='
        line: data_directory = '{{ pg_dir_data }}'

    - name: Проверка запуска Postgresql-server
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true
